name: Master
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2

    - name: Hugo Cross Poster
      id: dotnet-code-metrics
      uses: chrisreddington/hugocrossposter@main
      with:
        directoryPath: './content'
        recursiveSubdirectories: ${{ true }}
        baseUrl: 'www.cloudwithchris.com'
