name: Master
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2

    - name: Hugo Cross Poster
      id: dotnet-code-metrics
      uses: chrisreddington/hugocrossposter@main
      with:
        directoryPath: './content/'
        recursiveSubdirectories: 'true'
        devtoToken: ${{ secrets.DEVTO_INTEGRATION_TOKEN }}
        mediumAuthorId: ${{ secrets.MEDIUM_AUTHOR_ID }}
        mediumToken: ${{ secrets.MEDIUM_TOKEN }}
